/**
 * Create real "Business Expenses" and "Personal Expenses" parent categories
 * and migrate existing categories under them based on isBusinessDefault flag
 *
 * NOTE: This script uses proper UUIDs (auto-generated by Prisma/database).
 * It does NOT use hardcoded string IDs, which would fail UUID validation.
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface ParentCategoryConfig {
  name: string;
  type: 'INCOME' | 'EXPENSE';
  isBusinessDefault: boolean;
  sortOrder: number;
}

const PARENT_CATEGORIES: ParentCategoryConfig[] = [
  { name: 'Business Expenses', type: 'EXPENSE', isBusinessDefault: true, sortOrder: 0 },
  { name: 'Personal Expenses', type: 'EXPENSE', isBusinessDefault: false, sortOrder: 1 },
  { name: 'Business Income', type: 'INCOME', isBusinessDefault: true, sortOrder: 0 },
  { name: 'Personal Income', type: 'INCOME', isBusinessDefault: false, sortOrder: 1 },
];

async function main() {
  console.log('Creating parent categories and migrating existing categories...\n');

  // Map to store created parent IDs
  const parentIds: Map<string, string> = new Map();

  // Create or find parent categories
  for (const config of PARENT_CATEGORIES) {
    // First check if it already exists
    let parent = await prisma.account.findFirst({
      where: {
        name: config.name,
        type: config.type,
        kind: 'CATEGORY',
        parentId: null, // Must be top-level
      },
    });

    if (!parent) {
      // Create with auto-generated UUID
      parent = await prisma.account.create({
        data: {
          name: config.name,
          type: config.type,
          kind: 'CATEGORY',
          isBusinessDefault: config.isBusinessDefault,
          level: 0,
          fullPath: `${config.type}/${config.name}`,
          sortOrder: config.sortOrder,
        },
      });
      console.log(`✓ Created: ${config.name} (ID: ${parent.id})`);
    } else {
      console.log(`✓ Found existing: ${config.name} (ID: ${parent.id})`);
    }

    parentIds.set(config.name, parent.id);
  }

  console.log('');

  // Migrate existing EXPENSE categories (only root-level ones without parents)
  const expenseCategories = await prisma.account.findMany({
    where: {
      type: 'EXPENSE',
      kind: 'CATEGORY',
      parentId: null,
      name: {
        notIn: ['Business Expenses', 'Personal Expenses'],
      },
    },
  });

  console.log(`Found ${expenseCategories.length} root expense categories to migrate:`);

  for (const cat of expenseCategories) {
    const newParentName = cat.isBusinessDefault ? 'Business Expenses' : 'Personal Expenses';
    const newParentId = parentIds.get(newParentName);

    if (!newParentId) {
      console.error(`  ✗ Could not find parent "${newParentName}" for "${cat.name}"`);
      continue;
    }

    await prisma.account.update({
      where: { id: cat.id },
      data: {
        parentId: newParentId,
        level: 1,
        fullPath: `EXPENSE/${newParentName}/${cat.name}`,
      },
    });
    console.log(`  → Moved "${cat.name}" to ${newParentName}`);
  }

  // Migrate existing INCOME categories (only root-level ones without parents)
  const incomeCategories = await prisma.account.findMany({
    where: {
      type: 'INCOME',
      kind: 'CATEGORY',
      parentId: null,
      name: {
        notIn: ['Business Income', 'Personal Income'],
      },
    },
  });

  console.log(`\nFound ${incomeCategories.length} root income categories to migrate:`);

  for (const cat of incomeCategories) {
    const newParentName = cat.isBusinessDefault ? 'Business Income' : 'Personal Income';
    const newParentId = parentIds.get(newParentName);

    if (!newParentId) {
      console.error(`  ✗ Could not find parent "${newParentName}" for "${cat.name}"`);
      continue;
    }

    await prisma.account.update({
      where: { id: cat.id },
      data: {
        parentId: newParentId,
        level: 1,
        fullPath: `INCOME/${newParentName}/${cat.name}`,
      },
    });
    console.log(`  → Moved "${cat.name}" to ${newParentName}`);
  }

  console.log('\n✅ Migration complete!');
  console.log('\nNote: The sidebar will now show real parent categories.');
  console.log('You can move categories between Business and Personal using the Parent Category dropdown.');
}

main()
  .catch((e) => {
    console.error('Migration failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
